// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add_to_cart.proto

package com.learn.grpc.stubs;

public interface AddToCartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddToCartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_name = 1;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 1;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();
}
