// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add_to_cart.proto

package com.learn.grpc.stubs;

public interface AddToCartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddToCartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 product_id = 2;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>string product_name = 3;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 3;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  int getQuantity();
}
