// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add_to_cart.proto

package com.learn.grpc.stubs;

public final class AddToCart {
  private AddToCart() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddToCartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddToCartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddToCartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddToCartResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021add_to_cart.proto\"Z\n\020AddToCartRequest\022" +
      "\n\n\002id\030\001 \001(\005\022\022\n\nproduct_id\030\002 \001(\005\022\024\n\014produ" +
      "ct_name\030\003 \001(\t\022\020\n\010quantity\030\004 \001(\005\")\n\021AddTo" +
      "CartResponse\022\024\n\014product_name\030\001 \001(\t2F\n\020Ad" +
      "dToCartService\0222\n\taddToCart\022\021.AddToCartR" +
      "equest\032\022.AddToCartResponseB\030\n\024com.learn." +
      "grpc.stubsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AddToCartRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddToCartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddToCartRequest_descriptor,
        new java.lang.String[] { "Id", "ProductId", "ProductName", "Quantity", });
    internal_static_AddToCartResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddToCartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddToCartResponse_descriptor,
        new java.lang.String[] { "ProductName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
