// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.learn.grpc.stubs;

public final class ProductOuterClass {
  private ProductOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\"&\n\016ProductRequest\022\024\n\014pro" +
      "duct_name\030\002 \001(\t\",\n\017ProductResponse\022\031\n\007pr" +
      "oduct\030\001 \003(\0132\010.Product\"=\n\007Product\022\n\n\002id\030\001" +
      " \001(\005\022\024\n\014product_name\030\002 \001(\t\022\020\n\010quantity\030\003" +
      " \001(\0052H\n\016ProductService\0226\n\021getProductDeta" +
      "ils\022\017.ProductRequest\032\020.ProductResponseB\030" +
      "\n\024com.learn.grpc.stubsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductRequest_descriptor,
        new java.lang.String[] { "ProductName", });
    internal_static_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductResponse_descriptor,
        new java.lang.String[] { "Product", });
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "Id", "ProductName", "Quantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
