// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package com.learn.grpc.stubs;

public final class EmployeeServiceOuterClass {
  private EmployeeServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_resources_EmployeeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_resources_EmployeeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_resources_EmployeeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_resources_EmployeeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025EmployeeService.proto\022\022src.main.resour" +
      "ces\"+\n\017EmployeeRequest\022\n\n\002id\030\001 \001(\005\022\014\n\004na" +
      "me\030\002 \001(\t\">\n\020EmployeeResponse\022\n\n\002id\030\001 \001(\005" +
      "\022\014\n\004name\030\002 \001(\t\022\020\n\010jobTitle\030\003 \001(\t2k\n\017Empl" +
      "oyeeService\022X\n\013getEmployee\022#.src.main.re" +
      "sources.EmployeeRequest\032$.src.main.resou" +
      "rces.EmployeeResponseB\030\n\024com.learn.grpc." +
      "stubsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_src_main_resources_EmployeeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_src_main_resources_EmployeeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_resources_EmployeeRequest_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_src_main_resources_EmployeeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_src_main_resources_EmployeeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_resources_EmployeeResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "JobTitle", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
