// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.learn.grpc.stubs;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.learn.grpc.OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.learn.grpc.Order order = 1;</code>
   */
  java.util.List<Order>
      getOrderList();
  /**
   * <code>repeated .com.learn.grpc.Order order = 1;</code>
   */
  Order getOrder(int index);
  /**
   * <code>repeated .com.learn.grpc.Order order = 1;</code>
   */
  int getOrderCount();
  /**
   * <code>repeated .com.learn.grpc.Order order = 1;</code>
   */
  java.util.List<? extends OrderOrBuilder>
      getOrderOrBuilderList();
  /**
   * <code>repeated .com.learn.grpc.Order order = 1;</code>
   */
  OrderOrBuilder getOrderOrBuilder(
      int index);
}
