// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.learn.grpc.stubs;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.learn.grpc.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string userName = 2;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 2;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 4;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>.com.learn.grpc.Gender gender = 5;</code>
   * @return The enum numeric value on the wire for gender.
   */
  int getGenderValue();
  /**
   * <code>.com.learn.grpc.Gender gender = 5;</code>
   * @return The gender.
   */
  Gender getGender();

  /**
   * <code>int32 number_of_orders = 6;</code>
   * @return The numberOfOrders.
   */
  int getNumberOfOrders();
}
